version: '3.11'

services:
  app:
    build:
      context: src
      dockerfile: ../build/Dockerfile
    ports:
      - "3000:3000"
    healthcheck:
      test: "curl -f http://localhost:3000"
      interval: 1m
      timeout: 1m
